"""Bloomberg exchange suffix -> Country name mapping."""

EXCHANGE_TO_COUNTRY = {
    "AB": "Saudi Arabia",
    "AU": "Australia",
    "AV": "Austria",
    "BB": "Belgium",
    "BD": "Bangladesh",
    "BZ": "Brazil",
    "CH": "China",
    "CI": "Chile",
    "CN": "Canada",
    "EY": "Egypt",
    "FP": "France",
    "GA": "Greece",
    "GR": "Germany",
    "HB": "Hungary",
    "HK": "Hong Kong",
    "IJ": "Indonesia",
    "IN": "India",
    "JP": "Japan",
    "KK": "Kenya",
    "KN": "Kuwait",
    "KS": "South Korea",
    "KZ": "Kazakhstan",
    "LN": "United Kingdom",
    "MK": "Malaysia",
    "MM": "Mexico",
    "NA": "Netherlands",
    "NL": "Nigeria",
    "NO": "Norway",
    "NZ": "New Zealand",
    "PA": "Panama",
    "PE": "Peru",
    "PL": "Portugal",
    "PM": "Philippines",
    "PW": "Poland",
    "RM": "Russia",
    "RO": "Romania",
    "SJ": "South Africa",
    "SM": "Spain",
    "SP": "Singapore",
    "SS": "Saudi Arabia",
    "SW": "Switzerland",
    "TI": "Turkey",
    "TT": "Taiwan",
    "UH": "UAE",
    "US": "United States",
    "VN": "Vietnam",
}

# Bloomberg country code (2-letter) -> display name
COUNTRY_CODE_TO_NAME = {
    "AE": "UAE",
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BR": "Brazil",
    "CA": "Canada",
    "CH": "Switzerland",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "CZ": "Czech Republic",
    "DE": "Germany",
    "DK": "Denmark",
    "EG": "Egypt",
    "ES": "Spain",
    "FI": "Finland",
    "FR": "France",
    "GB": "United Kingdom",
    "GR": "Greece",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IN": "India",
    "IT": "Italy",
    "JP": "Japan",
    "KE": "Kenya",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",
    "LU": "Luxembourg",
    "MO": "Macau",
    "MX": "Mexico",
    "MY": "Malaysia",
    "NG": "Nigeria",
    "NL": "Netherlands",
    "NO": "Norway",
    "NZ": "New Zealand",
    "PA": "Panama",
    "PE": "Peru",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PT": "Portugal",
    "QA": "Qatar",
    "RO": "Romania",
    "RU": "Russia",
    "SA": "Saudi Arabia",
    "SE": "Sweden",
    "SG": "Singapore",
    "TH": "Thailand",
    "TR": "Turkey",
    "TW": "Taiwan",
    "US": "United States",
    "VN": "Vietnam",
    "ZA": "South Africa",
}


def get_country_from_exchange(exchange_code):
    if not exchange_code:
        return None
    return EXCHANGE_TO_COUNTRY.get(exchange_code.upper())


def get_country_from_bbg_code(country_code):
    if not country_code or not isinstance(country_code, str):
        return None
    return COUNTRY_CODE_TO_NAME.get(country_code.upper(), country_code)
